server:
  protocol: http
  host: {{ get_env(name = "SERVER_HOST", default = "127.0.0.1") }}
  port: {{ get_env(name = "SERVER_PORT", default = "7150") }}

database:
  uri: {{ get_env(name = "DATABASE_URL", default = "postgresql://username:password@localhost:5432/database") }}
  max_connections: {{ get_env(name = "DATABASE_MAX_CONNECTIONS", default = "10") }}
  min_connections: {{ get_env(name = "DATABASE_MIN_CONNECTIONS", default = "0") }}
  connection_timeout: {{ get_env(name = "DATABASE_CONNECTION_TIMEOUT", default = "5") }}
  idle_timeout: {{ get_env(name = "DATABASE_IDLE_TIMEOUT", default = "5") }}
  auto_migrate: {{ get_env(name = "DATABASE_AUTO_MIGRATE", default = "true") }}
  dangerously_truncate: {{ get_env(name = "DATABASE_DANGEROUSLY_TRUNCATE", default = "false") }}
  dangerously_recreate: {{ get_env(name = "DATABASE_DANGEROUSLY_RECREATE", default = "false") }}

logger:
  level: debug
  format: pretty
  crates:
    - auth
    - axum
    - sqlx
    - tower
    - tower_http

auth:
  access:
    private_key: secrets/keys/dev/access_key.pem
    public_key: secrets/keys/dev/access_key_pub.pem
    maxage: 900 # 15 Minutes
  refresh:
    private_key: secrets/keys/dev/refresh_key.pem
    public_key: secrets/keys/dev/refresh_key_pub.pem
    maxage: 604800 # 7 Days
