server:
  protocol: http
  host: 127.0.0.1
  port: 7151

logger:
  level: trace
  format: full
  crates:
    - auth
    - axum
    - sqlx
    - tower
    - tower_http
  # file_appender:
  # enable: true
  # non_blocking: true
  # rotation: daily # options: hourly, daily, weekly, monthly
  # directory: logs # default ./logs
  # filename_prefix: auth
  # filename_suffix: .log
  # max_log_files: 30

auth:
  access:
    private_key: secrets/keys/dev/access_key.pem
    public_key: secrets/keys/dev/access_key_pub.pem
    exp: 900 # 15 Minutes
  refresh:
    private_key: secrets/keys/dev/refresh_key.pem
    public_key: secrets/keys/dev/refresh_key_pub.pem
    exp: 604800 # 7 Days
